// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeLanguage from "../src/MeLanguage.res.js";
import * as MeTestUtils from "./MeTestUtils.res.js";

function testParseValueInteger() {
  let v = MeLanguage.parseValue("42");
  return MeTestUtils.assertEqual(v, {
    TAG: "Number",
    _0: 42.0
  }, "parseValue integer");
}

function testParseValueFloat() {
  let v = MeLanguage.parseValue("3.14");
  return MeTestUtils.assertEqual(v, {
    TAG: "Number",
    _0: 3.14
  }, "parseValue float");
}

function testParseValueNegative() {
  let v = MeLanguage.parseValue("-7");
  return MeTestUtils.assertEqual(v, {
    TAG: "Number",
    _0: -7.0
  }, "parseValue negative");
}

function testParseValueZero() {
  let v = MeLanguage.parseValue("0");
  return MeTestUtils.assertEqual(v, {
    TAG: "Number",
    _0: 0.0
  }, "parseValue zero");
}

function testParseValueString() {
  let v = MeLanguage.parseValue("hello");
  return MeTestUtils.assertEqual(v, {
    TAG: "String",
    _0: "hello"
  }, "parseValue non-numeric string");
}

function testParseValueEmptyString() {
  let v = MeLanguage.parseValue("");
  return MeTestUtils.assertEqual(v, {
    TAG: "String",
    _0: ""
  }, "parseValue empty string");
}

function testParseValueMixedText() {
  let v = MeLanguage.parseValue("abc123");
  return MeTestUtils.assertEqual(v, {
    TAG: "String",
    _0: "abc123"
  }, "parseValue mixed text");
}

function testValueToStringStr() {
  let s = MeLanguage.valueToString({
    TAG: "String",
    _0: "hi"
  });
  return MeTestUtils.assertEqual(s, "hi", "valueToString String");
}

function testValueToStringNum() {
  let s = MeLanguage.valueToString({
    TAG: "Number",
    _0: 5.0
  });
  return MeTestUtils.assertEqual(s, "5", "valueToString Number(5)");
}

function testInterpolateSingleVar() {
  let env = MeLanguage.createMeEnvironment();
  env.variables["name"] = {
    TAG: "String",
    _0: "Alex"
  };
  let result = MeLanguage.interpolate("Hello {name}!", env);
  return MeTestUtils.assertEqual(result, "Hello Alex!", "interpolate single variable");
}

function testInterpolateMultipleVars() {
  let env = MeLanguage.createMeEnvironment();
  env.variables["name"] = {
    TAG: "String",
    _0: "Alex"
  };
  env.variables["age"] = {
    TAG: "Number",
    _0: 10.0
  };
  let result = MeLanguage.interpolate("I am {name}, age {age}.", env);
  return MeTestUtils.assertEqual(result, "I am Alex, age 10.", "interpolate multiple variables");
}

function testInterpolateNoVars() {
  let env = MeLanguage.createMeEnvironment();
  let result = MeLanguage.interpolate("No variables here.", env);
  return MeTestUtils.assertEqual(result, "No variables here.", "interpolate no variables");
}

function testInterpolateUnknownVar() {
  let env = MeLanguage.createMeEnvironment();
  let result = MeLanguage.interpolate("Hello {unknown}!", env);
  return MeTestUtils.assertEqual(result, "Hello {unknown}!", "interpolate unknown variable kept");
}

function testInterpolateAdjacentVars() {
  let env = MeLanguage.createMeEnvironment();
  env.variables["a"] = {
    TAG: "String",
    _0: "X"
  };
  env.variables["b"] = {
    TAG: "String",
    _0: "Y"
  };
  let result = MeLanguage.interpolate("{a}{b}", env);
  return MeTestUtils.assertEqual(result, "XY", "interpolate adjacent variables");
}

function testInterpolateEmptyString() {
  let env = MeLanguage.createMeEnvironment();
  let result = MeLanguage.interpolate("", env);
  return MeTestUtils.assertEqual(result, "", "interpolate empty string");
}

function testInterpolateBracesNoVar() {
  let env = MeLanguage.createMeEnvironment();
  let result = MeLanguage.interpolate("Use {} for fun", env);
  return MeTestUtils.assertEqual(result === "Use {} for fun" || result === "Use  for fun", true, "interpolate empty braces");
}

function run() {
  return [
    MeTestUtils.runTest("parseValue: integer", testParseValueInteger),
    MeTestUtils.runTest("parseValue: float", testParseValueFloat),
    MeTestUtils.runTest("parseValue: negative", testParseValueNegative),
    MeTestUtils.runTest("parseValue: zero", testParseValueZero),
    MeTestUtils.runTest("parseValue: string", testParseValueString),
    MeTestUtils.runTest("parseValue: empty string", testParseValueEmptyString),
    MeTestUtils.runTest("parseValue: mixed text", testParseValueMixedText),
    MeTestUtils.runTest("valueToString: String", testValueToStringStr),
    MeTestUtils.runTest("valueToString: Number", testValueToStringNum),
    MeTestUtils.runTest("interpolate: single var", testInterpolateSingleVar),
    MeTestUtils.runTest("interpolate: multiple vars", testInterpolateMultipleVars),
    MeTestUtils.runTest("interpolate: no vars", testInterpolateNoVars),
    MeTestUtils.runTest("interpolate: unknown var", testInterpolateUnknownVar),
    MeTestUtils.runTest("interpolate: adjacent vars", testInterpolateAdjacentVars),
    MeTestUtils.runTest("interpolate: empty string", testInterpolateEmptyString),
    MeTestUtils.runTest("interpolate: empty braces", testInterpolateBracesNoVar)
  ];
}

export {
  testParseValueInteger,
  testParseValueFloat,
  testParseValueNegative,
  testParseValueZero,
  testParseValueString,
  testParseValueEmptyString,
  testParseValueMixedText,
  testValueToStringStr,
  testValueToStringNum,
  testInterpolateSingleVar,
  testInterpolateMultipleVars,
  testInterpolateNoVars,
  testInterpolateUnknownVar,
  testInterpolateAdjacentVars,
  testInterpolateEmptyString,
  testInterpolateBracesNoVar,
  run,
}
/* No side effect */
