// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeTestUtils from "./MeTestUtils.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testWhenMatchesFirst() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("animal", "dog"),
    MeTestUtils.choose([
      MeTestUtils.when_("animal", "dog", [MeTestUtils.say("Woof!")]),
      MeTestUtils.when_("animal", "cat", [MeTestUtils.say("Meow!")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Woof!"], "when matches first branch");
}

function testWhenMatchesSecond() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("animal", "cat"),
    MeTestUtils.choose([
      MeTestUtils.when_("animal", "dog", [MeTestUtils.say("Woof!")]),
      MeTestUtils.when_("animal", "cat", [MeTestUtils.say("Meow!")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Meow!"], "when matches second branch");
}

function testWhenNoMatch() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("animal", "fish"),
    MeTestUtils.choose([
      MeTestUtils.when_("animal", "dog", [MeTestUtils.say("Woof!")]),
      MeTestUtils.when_("animal", "cat", [MeTestUtils.say("Meow!")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, [], "when no match produces no output");
}

function testOtherwiseFallback() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("color", "green"),
    MeTestUtils.choose([
      MeTestUtils.when_("color", "red", [MeTestUtils.say("Red!")]),
      MeTestUtils.when_("color", "blue", [MeTestUtils.say("Blue!")]),
      MeTestUtils.otherwise([MeTestUtils.say("Something else!")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Something else!"], "otherwise fallback");
}

function testOtherwiseNotReachedWhenMatched() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("color", "red"),
    MeTestUtils.choose([
      MeTestUtils.when_("color", "red", [MeTestUtils.say("Red!")]),
      MeTestUtils.otherwise([MeTestUtils.say("Fallback")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Red!"], "otherwise not reached when matched");
}

function testWhenIsNot() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("mood", "happy"),
    MeTestUtils.choose([
      MeTestUtils.whenNot("mood", "sad", [MeTestUtils.say("Not sad!")]),
      MeTestUtils.otherwise([MeTestUtils.say("Fallback")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Not sad!"], "when-is-not condition true");
}

function testWhenIsNotFalse() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("mood", "sad"),
    MeTestUtils.choose([
      MeTestUtils.whenNot("mood", "sad", [MeTestUtils.say("Not sad!")]),
      MeTestUtils.otherwise([MeTestUtils.say("Sad indeed")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Sad indeed"], "when-is-not condition false, falls to otherwise");
}

function testWhenIsNotUndefinedVar() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.choose([
      MeTestUtils.whenNot("missing", "anything", [MeTestUtils.say("Missing is not anything!")]),
      MeTestUtils.otherwise([MeTestUtils.say("Fallback")])
    ])]));
  return MeTestUtils.assertEqual(env.output, ["Missing is not anything!"], "when-is-not with undefined var");
}

function testWhenMultipleChildren() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("weather", "sunny"),
    MeTestUtils.choose([MeTestUtils.when_("weather", "sunny", [
        MeTestUtils.say("It's sunny!"),
        MeTestUtils.say("Wear sunscreen!"),
        MeTestUtils.say("Have fun outside!")
      ])])
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "It's sunny!",
    "Wear sunscreen!",
    "Have fun outside!"
  ], "when executes all children");
}

function testWhenNumericValue() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("score", "100"),
    MeTestUtils.choose([
      MeTestUtils.when_("score", "100", [MeTestUtils.say("Perfect!")]),
      MeTestUtils.otherwise([MeTestUtils.say("Try again")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["Perfect!"], "when with numeric value");
}

function testNestedChoose() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("day", "saturday"),
    MeTestUtils.remember("weather", "sunny"),
    MeTestUtils.choose([
      MeTestUtils.when_("day", "saturday", [
        MeTestUtils.say("It's Saturday!"),
        MeTestUtils.choose([
          MeTestUtils.when_("weather", "sunny", [MeTestUtils.say("Go to the park!")]),
          MeTestUtils.otherwise([MeTestUtils.say("Stay home")])
        ])
      ]),
      MeTestUtils.otherwise([MeTestUtils.say("Workday")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "It's Saturday!",
    "Go to the park!"
  ], "nested choose both levels match");
}

function testChooseEmpty() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.choose([])]));
  return MeTestUtils.assertEqual(env.output, [], "empty choose no output");
}

function testWhenNoAttributes() {
  let node = MeTestUtils.makeNode("When", Primitive_option.some([MeTestUtils.say("should not appear")]), undefined, undefined, undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.choose([
      node,
      MeTestUtils.otherwise([MeTestUtils.say("fallback")])
    ])]));
  return MeTestUtils.assertEqual(env.output, ["fallback"], "when with no attributes falls through");
}

function testFirstMatchWins() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "a"),
    MeTestUtils.choose([
      MeTestUtils.when_("x", "a", [MeTestUtils.say("first")]),
      MeTestUtils.when_("x", "a", [MeTestUtils.say("second")]),
      MeTestUtils.otherwise([MeTestUtils.say("third")])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, ["first"], "first matching when wins");
}

function run() {
  return [
    MeTestUtils.runTest("Cond: when matches first", testWhenMatchesFirst),
    MeTestUtils.runTest("Cond: when matches second", testWhenMatchesSecond),
    MeTestUtils.runTest("Cond: when no match", testWhenNoMatch),
    MeTestUtils.runTest("Cond: otherwise fallback", testOtherwiseFallback),
    MeTestUtils.runTest("Cond: otherwise not reached", testOtherwiseNotReachedWhenMatched),
    MeTestUtils.runTest("Cond: when-is-not true", testWhenIsNot),
    MeTestUtils.runTest("Cond: when-is-not false", testWhenIsNotFalse),
    MeTestUtils.runTest("Cond: when-is-not undefined var", testWhenIsNotUndefinedVar),
    MeTestUtils.runTest("Cond: when multiple children", testWhenMultipleChildren),
    MeTestUtils.runTest("Cond: when numeric value", testWhenNumericValue),
    MeTestUtils.runTest("Cond: nested choose", testNestedChoose),
    MeTestUtils.runTest("Cond: empty choose", testChooseEmpty),
    MeTestUtils.runTest("Cond: when no attributes", testWhenNoAttributes),
    MeTestUtils.runTest("Cond: first match wins", testFirstMatchWins)
  ];
}

export {
  testWhenMatchesFirst,
  testWhenMatchesSecond,
  testWhenNoMatch,
  testOtherwiseFallback,
  testOtherwiseNotReachedWhenMatched,
  testWhenIsNot,
  testWhenIsNotFalse,
  testWhenIsNotUndefinedVar,
  testWhenMultipleChildren,
  testWhenNumericValue,
  testNestedChoose,
  testChooseEmpty,
  testWhenNoAttributes,
  testFirstMatchWins,
  run,
}
/* No side effect */
