// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeTestUtils from "./MeTestUtils.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testRepeatThreeTimes() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.repeat(3, [MeTestUtils.say("Go!")])]));
  return MeTestUtils.assertEqual(env.output, [
    "Go!",
    "Go!",
    "Go!"
  ], "repeat 3 times");
}

function testRepeatOnce() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.repeat(1, [MeTestUtils.say("Once")])]));
  return MeTestUtils.assertEqual(env.output, ["Once"], "repeat 1 time");
}

function testRepeatZeroTimes() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.repeat(0, [MeTestUtils.say("Never")])]));
  return MeTestUtils.assertEqual(env.output, [], "repeat 0 times produces nothing");
}

function testRepeatWithCounter() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("count", "0"),
    MeTestUtils.repeat(5, [MeTestUtils.add("count", "1")]),
    MeTestUtils.say("Count: {count}")
  ]));
  return MeTestUtils.assertEqual(env.output, ["Count: 5"], "repeat with counter");
}

function testRepeatWithAdd() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("score", "0"),
    MeTestUtils.repeat(3, [MeTestUtils.add("score", "10")])
  ]));
  return MeTestUtils.assertEqual(env.variables["score"], {
    TAG: "Number",
    _0: 30.0
  }, "repeat adds 10 three times = 30");
}

function testRepeatWithSubtract() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("hp", "100"),
    MeTestUtils.repeat(4, [MeTestUtils.subtract("hp", "15")])
  ]));
  return MeTestUtils.assertEqual(env.variables["hp"], {
    TAG: "Number",
    _0: 40.0
  }, "repeat subtracts 15 four times = 40");
}

function testRepeatMultipleChildren() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("n", "0"),
    MeTestUtils.repeat(2, [
      MeTestUtils.add("n", "1"),
      MeTestUtils.say("Step {n}")
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "Step 1",
    "Step 2"
  ], "repeat with add and say");
}

function testNestedRepeat() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("total", "0"),
    MeTestUtils.repeat(3, [MeTestUtils.repeat(2, [MeTestUtils.add("total", "1")])])
  ]));
  return MeTestUtils.assertEqual(env.variables["total"], {
    TAG: "Number",
    _0: 6.0
  }, "nested repeat 3x2 = 6");
}

function testRepeatStopsEarly() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("i", "0"),
    MeTestUtils.repeat(10, [
      MeTestUtils.add("i", "1"),
      MeTestUtils.say("Iteration {i}"),
      MeTestUtils.choose([MeTestUtils.when_("i", "2", [MeTestUtils.stop()])])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "Iteration 1",
    "Iteration 2"
  ], "repeat stops early with stop");
}

function testRepeatNonNumericTimes() {
  let attrs = {};
  attrs["times"] = "abc";
  let node = MeTestUtils.makeNode("Repeat", Primitive_option.some([MeTestUtils.say("never")]), Primitive_option.some(attrs), undefined, undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(env.output, [], "repeat with non-numeric times does nothing");
}

function testRepeatNoTimesAttribute() {
  let node = MeTestUtils.makeNode("Repeat", Primitive_option.some([MeTestUtils.say("never")]), undefined, undefined, undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(env.output, [], "repeat without times attribute does nothing");
}

function testRepeatNoChildren() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.repeat(5, [])]));
  return MeTestUtils.assertEqual(env.output, [], "repeat with no children does nothing");
}

function testRepeatLarge() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("sum", "0"),
    MeTestUtils.repeat(100, [MeTestUtils.add("sum", "1")])
  ]));
  return MeTestUtils.assertEqual(env.variables["sum"], {
    TAG: "Number",
    _0: 100.0
  }, "repeat 100 times counting");
}

function testRepeatWithChoose() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("n", "0"),
    MeTestUtils.repeat(4, [
      MeTestUtils.add("n", "1"),
      MeTestUtils.choose([
        MeTestUtils.when_("n", "1", [MeTestUtils.say("one")]),
        MeTestUtils.when_("n", "2", [MeTestUtils.say("two")]),
        MeTestUtils.otherwise([MeTestUtils.say("more")])
      ])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "one",
    "two",
    "more",
    "more"
  ], "repeat with choose inside");
}

function run() {
  return [
    MeTestUtils.runTest("Repeat: three times", testRepeatThreeTimes),
    MeTestUtils.runTest("Repeat: once", testRepeatOnce),
    MeTestUtils.runTest("Repeat: zero times", testRepeatZeroTimes),
    MeTestUtils.runTest("Repeat: with counter", testRepeatWithCounter),
    MeTestUtils.runTest("Repeat: with add", testRepeatWithAdd),
    MeTestUtils.runTest("Repeat: with subtract", testRepeatWithSubtract),
    MeTestUtils.runTest("Repeat: multiple children", testRepeatMultipleChildren),
    MeTestUtils.runTest("Repeat: nested", testNestedRepeat),
    MeTestUtils.runTest("Repeat: stops early", testRepeatStopsEarly),
    MeTestUtils.runTest("Repeat: non-numeric times", testRepeatNonNumericTimes),
    MeTestUtils.runTest("Repeat: no times attribute", testRepeatNoTimesAttribute),
    MeTestUtils.runTest("Repeat: no children", testRepeatNoChildren),
    MeTestUtils.runTest("Repeat: large (100)", testRepeatLarge),
    MeTestUtils.runTest("Repeat: with choose inside", testRepeatWithChoose)
  ];
}

export {
  testRepeatThreeTimes,
  testRepeatOnce,
  testRepeatZeroTimes,
  testRepeatWithCounter,
  testRepeatWithAdd,
  testRepeatWithSubtract,
  testRepeatMultipleChildren,
  testNestedRepeat,
  testRepeatStopsEarly,
  testRepeatNonNumericTimes,
  testRepeatNoTimesAttribute,
  testRepeatNoChildren,
  testRepeatLarge,
  testRepeatWithChoose,
  run,
}
/* No side effect */
