// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeLanguage from "../src/MeLanguage.res.js";
import * as MeTestUtils from "./MeTestUtils.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testRememberMissingName() {
  let attrs = {};
  let node = MeTestUtils.makeNode("Remember", undefined, Primitive_option.some(attrs), "orphan", undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(Object.entries(env.variables).length, 0, "remember missing name attr");
}

function testAddMissingTo() {
  let attrs = {};
  let node = MeTestUtils.makeNode("Add", undefined, Primitive_option.some(attrs), "5", undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "10"),
    node
  ]));
  return MeTestUtils.assertEqual(env.variables["x"], {
    TAG: "Number",
    _0: 10.0
  }, "add missing to attr leaves vars unchanged");
}

function testSubtractMissingFrom() {
  let attrs = {};
  let node = MeTestUtils.makeNode("Subtract", undefined, Primitive_option.some(attrs), "5", undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "10"),
    node
  ]));
  return MeTestUtils.assertEqual(env.variables["x"], {
    TAG: "Number",
    _0: 10.0
  }, "subtract missing from attr leaves vars unchanged");
}

function testAddNonNumericAmount() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "10"),
    MeTestUtils.add("x", "abc")
  ]));
  return MeTestUtils.assertEqual(env.variables["x"], {
    TAG: "Number",
    _0: 10.0
  }, "add non-numeric amount unchanged");
}

function testSubtractNonNumericAmount() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "10"),
    MeTestUtils.subtract("x", "abc")
  ]));
  return MeTestUtils.assertEqual(env.variables["x"], {
    TAG: "Number",
    _0: 10.0
  }, "subtract non-numeric amount unchanged");
}

function testWhenStandalone() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.when_("x", "1", [MeTestUtils.say("should not appear")])]));
  return MeTestUtils.assertEqual(env.output, [], "when standalone does nothing");
}

function testOtherwiseStandalone() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.otherwise([MeTestUtils.say("should not appear")])]));
  return MeTestUtils.assertEqual(env.output, [], "otherwise standalone does nothing");
}

function testShapeStandalone() {
  let node = MeTestUtils.shape("circle", [[
      "r",
      "10"
    ]]);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(env.canvas, [], "shape standalone does nothing");
}

function testStoppedStatePropagates() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.say("A"),
    MeTestUtils.stop(),
    MeTestUtils.say("B"),
    MeTestUtils.remember("x", "should-not-set"),
    MeTestUtils.repeat(5, [MeTestUtils.say("nope")])
  ]));
  if (MeTestUtils.assertEqual(env.output, ["A"], "stopped: only A appears") && MeTestUtils.assertEqual(env.variables["x"], undefined, "stopped: var not set")) {
    return MeTestUtils.assertEqual(env.stopped, true, "stopped: flag true");
  } else {
    return false;
  }
}

function testStoppedBeforeProgram() {
  let env = MeLanguage.createMeEnvironment();
  env.stopped = true;
  MeLanguage.execute(MeTestUtils.program([MeTestUtils.say("invisible")]), env);
  return MeTestUtils.assertEqual(env.output, [], "pre-stopped env produces no output");
}

function testInterpolateSpecialChars() {
  let env = MeLanguage.createMeEnvironment();
  env.variables["greeting"] = {
    TAG: "String",
    _0: "Hello <world> & \"friends\""
  };
  let result = MeLanguage.interpolate("{greeting}", env);
  return MeTestUtils.assertEqual(result, "Hello <world> & \"friends\"", "interpolate preserves special chars");
}

function testInterpolateNumberFormatting() {
  let env = MeLanguage.createMeEnvironment();
  env.variables["pi"] = {
    TAG: "Number",
    _0: 3.14
  };
  let result = MeLanguage.interpolate("Pi is {pi}", env);
  return MeTestUtils.assertEqual(result.startsWith("Pi is 3.14"), true, "interpolate number formatting");
}

function testInterpolateHyphenatedVar() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("my-name", "Alex"),
    MeTestUtils.say("Hello {my-name}!")
  ]));
  return MeTestUtils.assertEqual(env.output, ["Hello Alex!"], "interpolate hyphenated variable name");
}

function testCanvasIgnoresNonShapeChildren() {
  let sayNode = MeTestUtils.say("not a shape");
  let canvasNode = MeTestUtils.canvas("100", "100", [sayNode]);
  let env = MeTestUtils.runProgram(MeTestUtils.program([canvasNode]));
  return MeTestUtils.assertEqual(env.canvas, [], "canvas ignores non-shape children");
}

function testComplexProgram() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("name", "Me"),
    MeTestUtils.remember("hp", "100"),
    MeTestUtils.remember("potions", "3"),
    MeTestUtils.say("Welcome, {name}!"),
    MeTestUtils.say("HP: {hp}, Potions: {potions}"),
    MeTestUtils.subtract("hp", "30"),
    MeTestUtils.say("Ouch! HP now: {hp}"),
    MeTestUtils.choose([
      MeTestUtils.when_("potions", "0", [MeTestUtils.say("No potions left!")]),
      MeTestUtils.otherwise([
        MeTestUtils.add("hp", "20"),
        MeTestUtils.subtract("potions", "1"),
        MeTestUtils.say("Used potion! HP: {hp}, Potions: {potions}")
      ])
    ])
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "Welcome, Me!",
    "HP: 100, Potions: 3",
    "Ouch! HP now: 70",
    "Used potion! HP: 90, Potions: 2"
  ], "complex combined program");
}

function testProgramNullChildren() {
  let node = MeTestUtils.makeNode("Program", undefined, undefined, undefined, undefined);
  let env = MeTestUtils.runProgram(node);
  return MeTestUtils.assertEqual(env.output, [], "program with None children");
}

function run() {
  return [
    MeTestUtils.runTest("Edge: remember missing name attr", testRememberMissingName),
    MeTestUtils.runTest("Edge: add missing to attr", testAddMissingTo),
    MeTestUtils.runTest("Edge: subtract missing from attr", testSubtractMissingFrom),
    MeTestUtils.runTest("Edge: add non-numeric amount", testAddNonNumericAmount),
    MeTestUtils.runTest("Edge: subtract non-numeric amount", testSubtractNonNumericAmount),
    MeTestUtils.runTest("Edge: when standalone (no-op)", testWhenStandalone),
    MeTestUtils.runTest("Edge: otherwise standalone (no-op)", testOtherwiseStandalone),
    MeTestUtils.runTest("Edge: shape standalone (no-op)", testShapeStandalone),
    MeTestUtils.runTest("Edge: stopped propagates", testStoppedStatePropagates),
    MeTestUtils.runTest("Edge: pre-stopped env", testStoppedBeforeProgram),
    MeTestUtils.runTest("Edge: interpolate special chars", testInterpolateSpecialChars),
    MeTestUtils.runTest("Edge: interpolate number format", testInterpolateNumberFormatting),
    MeTestUtils.runTest("Edge: interpolate hyphenated var", testInterpolateHyphenatedVar),
    MeTestUtils.runTest("Edge: canvas ignores non-shapes", testCanvasIgnoresNonShapeChildren),
    MeTestUtils.runTest("Edge: complex combined program", testComplexProgram),
    MeTestUtils.runTest("Edge: program with None children", testProgramNullChildren)
  ];
}

export {
  testRememberMissingName,
  testAddMissingTo,
  testSubtractMissingFrom,
  testAddNonNumericAmount,
  testSubtractNonNumericAmount,
  testWhenStandalone,
  testOtherwiseStandalone,
  testShapeStandalone,
  testStoppedStatePropagates,
  testStoppedBeforeProgram,
  testInterpolateSpecialChars,
  testInterpolateNumberFormatting,
  testInterpolateHyphenatedVar,
  testCanvasIgnoresNonShapeChildren,
  testComplexProgram,
  testProgramNullChildren,
  run,
}
/* No side effect */
