// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeLanguage from "../src/MeLanguage.res.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeNode(nodeType, childrenOpt, attributesOpt, contentOpt, param) {
  let children = childrenOpt !== undefined ? Primitive_option.valFromOption(childrenOpt) : undefined;
  let attributes = attributesOpt !== undefined ? Primitive_option.valFromOption(attributesOpt) : undefined;
  let content = contentOpt !== undefined ? Primitive_option.valFromOption(contentOpt) : undefined;
  return {
    nodeType: nodeType,
    children: children,
    attributes: attributes,
    content: content
  };
}

function program(children) {
  return makeNode("Program", Primitive_option.some(children), undefined, undefined, undefined);
}

function say(text) {
  return makeNode("Say", undefined, undefined, Primitive_option.some(text), undefined);
}

function remember(name, value) {
  let attrs = {};
  attrs["name"] = name;
  return makeNode("Remember", undefined, Primitive_option.some(attrs), Primitive_option.some(value), undefined);
}

function add(varName, amount) {
  let attrs = {};
  attrs["to"] = varName;
  return makeNode("Add", undefined, Primitive_option.some(attrs), Primitive_option.some(amount), undefined);
}

function subtract(varName, amount) {
  let attrs = {};
  attrs["from"] = varName;
  return makeNode("Subtract", undefined, Primitive_option.some(attrs), Primitive_option.some(amount), undefined);
}

function repeat(times, children) {
  let attrs = {};
  attrs["times"] = times.toString();
  return makeNode("Repeat", Primitive_option.some(children), Primitive_option.some(attrs), undefined, undefined);
}

function stop() {
  return makeNode("Stop", undefined, undefined, undefined, undefined);
}

function ask(varName, prompt) {
  let attrs = {};
  attrs["into"] = varName;
  return makeNode("Ask", undefined, Primitive_option.some(attrs), Primitive_option.some(prompt), undefined);
}

function when_(varName, expectedValue, children) {
  let attrs = {};
  attrs[varName + "-is"] = expectedValue;
  return makeNode("When", Primitive_option.some(children), Primitive_option.some(attrs), undefined, undefined);
}

function whenNot(varName, notValue, children) {
  let attrs = {};
  attrs[varName + "-is-not"] = notValue;
  return makeNode("When", Primitive_option.some(children), Primitive_option.some(attrs), undefined, undefined);
}

function otherwise(children) {
  return makeNode("Otherwise", Primitive_option.some(children), undefined, undefined, undefined);
}

function choose(children) {
  return makeNode("Choose", Primitive_option.some(children), undefined, undefined, undefined);
}

function canvas(width, height, children) {
  let attrs = {};
  attrs["width"] = width;
  attrs["height"] = height;
  return makeNode("Canvas", Primitive_option.some(children), Primitive_option.some(attrs), undefined, undefined);
}

function shape(shapeType, props) {
  let attrs = {};
  attrs["type"] = shapeType;
  props.forEach(param => {
    attrs[param[0]] = param[1];
  });
  return makeNode("Shape", undefined, Primitive_option.some(attrs), undefined, undefined);
}

function runProgram(prog) {
  let env = MeLanguage.createMeEnvironment();
  MeLanguage.execute(prog, env);
  return env;
}

function assertEqual(actual, expected, label) {
  if (Primitive_object.equal(actual, expected)) {
    return true;
  } else {
    console.error(`FAIL: ` + label);
    return false;
  }
}

function runTest(name, fn) {
  let passed;
  try {
    passed = fn();
  } catch (exn) {
    passed = false;
  }
  return {
    name: name,
    passed: passed
  };
}

function summarise(results) {
  let total = results.length;
  let passed = results.filter(r => r.passed).length;
  let failed = total - passed | 0;
  console.log("");
  console.log(`--- Me Language Test Results ---`);
  results.forEach(r => {
    let icon = r.passed ? "  PASS" : "  FAIL";
    console.log(icon + `: ` + r.name);
  });
  console.log("");
  console.log(`Total: ` + total.toString() + `  Passed: ` + passed.toString() + `  Failed: ` + failed.toString());
  if (failed > 0) {
    return 1;
  } else {
    return 0;
  }
}

export {
  makeNode,
  program,
  say,
  remember,
  add,
  subtract,
  repeat,
  stop,
  ask,
  when_,
  whenNot,
  otherwise,
  choose,
  canvas,
  shape,
  runProgram,
  assertEqual,
  runTest,
  summarise,
}
/* No side effect */
