// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeLanguage from "../src/MeLanguage.res.js";
import * as MeTestUtils from "./MeTestUtils.res.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function testCreateEnvironment() {
  let env = MeLanguage.createMeEnvironment();
  if (MeTestUtils.assertEqual(env.output, [], "new env output empty") && MeTestUtils.assertEqual(env.canvas, [], "new env canvas empty")) {
    return MeTestUtils.assertEqual(env.stopped, false, "new env not stopped");
  } else {
    return false;
  }
}

function testSaySimple() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.say("Hello!")]));
  return MeTestUtils.assertEqual(env.output, ["Hello!"], "say simple output");
}

function testSayMultiple() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.say("Line 1"),
    MeTestUtils.say("Line 2"),
    MeTestUtils.say("Line 3")
  ]));
  return MeTestUtils.assertEqual(env.output, [
    "Line 1",
    "Line 2",
    "Line 3"
  ], "say multiple lines");
}

function testSayEmpty() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.say("")]));
  return MeTestUtils.assertEqual(env.output, [""], "say empty string");
}

function testSayWithInterpolation() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("pet", "cat"),
    MeTestUtils.say("My pet is a {pet}!")
  ]));
  return MeTestUtils.assertEqual(env.output, ["My pet is a cat!"], "say with variable interpolation");
}

function testSayNoContent() {
  let node = MeTestUtils.makeNode("Say", undefined, undefined, undefined, undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(env.output, [], "say with no content produces nothing");
}

function testRememberString() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.remember("color", "blue")]));
  let v = env.variables["color"];
  return MeTestUtils.assertEqual(v, {
    TAG: "String",
    _0: "blue"
  }, "remember stores string");
}

function testRememberNumber() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.remember("age", "10")]));
  let v = env.variables["age"];
  return MeTestUtils.assertEqual(v, {
    TAG: "Number",
    _0: 10.0
  }, "remember stores number");
}

function testRememberOverwrite() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "first"),
    MeTestUtils.remember("x", "second")
  ]));
  let v = env.variables["x"];
  return MeTestUtils.assertEqual(v, {
    TAG: "String",
    _0: "second"
  }, "remember overwrites previous");
}

function testRememberNoName() {
  let node = MeTestUtils.makeNode("Remember", undefined, undefined, "orphan", undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(Object.entries(env.variables).length, 0, "remember without name does nothing");
}

function testRememberNoContent() {
  let attrs = {};
  attrs["name"] = "x";
  let node = MeTestUtils.makeNode("Remember", undefined, Primitive_option.some(attrs), undefined, undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(env.variables["x"], undefined, "remember without content does nothing");
}

function testAddBasic() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("score", "0"),
    MeTestUtils.add("score", "10")
  ]));
  return MeTestUtils.assertEqual(env.variables["score"], {
    TAG: "Number",
    _0: 10.0
  }, "add basic");
}

function testAddMultiple() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("n", "5"),
    MeTestUtils.add("n", "3"),
    MeTestUtils.add("n", "2")
  ]));
  return MeTestUtils.assertEqual(env.variables["n"], {
    TAG: "Number",
    _0: 10.0
  }, "add multiple times");
}

function testAddToNonexistent() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.add("missing", "5")]));
  return MeTestUtils.assertEqual(env.variables["missing"], undefined, "add to nonexistent var");
}

function testAddToString() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("name", "Alex"),
    MeTestUtils.add("name", "5")
  ]));
  return MeTestUtils.assertEqual(env.variables["name"], {
    TAG: "String",
    _0: "Alex"
  }, "add to string var unchanged");
}

function testAddNoAttributes() {
  let node = MeTestUtils.makeNode("Add", undefined, undefined, "5", undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(env.output, [], "add with no attrs no crash");
}

function testSubtractBasic() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("lives", "3"),
    MeTestUtils.subtract("lives", "1")
  ]));
  return MeTestUtils.assertEqual(env.variables["lives"], {
    TAG: "Number",
    _0: 2.0
  }, "subtract basic");
}

function testSubtractToNegative() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.remember("x", "2"),
    MeTestUtils.subtract("x", "5")
  ]));
  return MeTestUtils.assertEqual(env.variables["x"], {
    TAG: "Number",
    _0: -3.0
  }, "subtract to negative");
}

function testSubtractFromNonexistent() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.subtract("missing", "1")]));
  return MeTestUtils.assertEqual(env.variables["missing"], undefined, "subtract from nonexistent");
}

function testAskStoresPlaceholder() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.ask("answer", "What is your name?")]));
  return MeTestUtils.assertEqual(env.variables["answer"], {
    TAG: "String",
    _0: "user-input"
  }, "ask stores placeholder");
}

function testAskNoInto() {
  let node = MeTestUtils.makeNode("Ask", undefined, undefined, "question?", undefined);
  let env = MeTestUtils.runProgram(MeTestUtils.program([node]));
  return MeTestUtils.assertEqual(Object.entries(env.variables).length, 0, "ask without into does nothing");
}

function testStopHalts() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([
    MeTestUtils.say("before"),
    MeTestUtils.stop(),
    MeTestUtils.say("after")
  ]));
  if (MeTestUtils.assertEqual(env.output, ["before"], "stop halts - only before")) {
    return MeTestUtils.assertEqual(env.stopped, true, "env marked stopped");
  } else {
    return false;
  }
}

function testStopInRepeat() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.repeat(100, [
      MeTestUtils.say("tick"),
      MeTestUtils.stop()
    ])]));
  return MeTestUtils.assertEqual(env.output, ["tick"], "stop inside repeat halts loop");
}

function testCanvasExecution() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.canvas("200", "100", [
      MeTestUtils.shape("circle", [
        [
          "cx",
          "50"
        ],
        [
          "cy",
          "50"
        ],
        [
          "r",
          "20"
        ]
      ]),
      MeTestUtils.shape("rect", [
        [
          "x",
          "10"
        ],
        [
          "y",
          "10"
        ],
        [
          "w",
          "30"
        ],
        [
          "h",
          "30"
        ]
      ])
    ])]));
  return MeTestUtils.assertEqual(env.canvas.length, 2, "canvas produces two commands");
}

function testCanvasShapeType() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.canvas("100", "100", [MeTestUtils.shape("circle", [[
          "r",
          "10"
        ]])])]));
  let first = env.canvas[0];
  if (first !== undefined) {
    return MeTestUtils.assertEqual(first.shape, "circle", "canvas shape type");
  } else {
    return MeTestUtils.assertEqual(true, false, "canvas should have one command");
  }
}

function testCanvasEmpty() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([MeTestUtils.canvas("100", "100", [])]));
  return MeTestUtils.assertEqual(env.canvas.length, 0, "empty canvas no commands");
}

function testEmptyProgramExecution() {
  let env = MeTestUtils.runProgram(MeTestUtils.program([]));
  if (MeTestUtils.assertEqual(env.output, [], "empty program no output")) {
    return MeTestUtils.assertEqual(env.stopped, false, "empty program not stopped");
  } else {
    return false;
  }
}

function run() {
  return [
    MeTestUtils.runTest("Exec: create environment", testCreateEnvironment),
    MeTestUtils.runTest("Exec: say simple", testSaySimple),
    MeTestUtils.runTest("Exec: say multiple", testSayMultiple),
    MeTestUtils.runTest("Exec: say empty string", testSayEmpty),
    MeTestUtils.runTest("Exec: say with interpolation", testSayWithInterpolation),
    MeTestUtils.runTest("Exec: say no content", testSayNoContent),
    MeTestUtils.runTest("Exec: remember string", testRememberString),
    MeTestUtils.runTest("Exec: remember number", testRememberNumber),
    MeTestUtils.runTest("Exec: remember overwrite", testRememberOverwrite),
    MeTestUtils.runTest("Exec: remember no name", testRememberNoName),
    MeTestUtils.runTest("Exec: remember no content", testRememberNoContent),
    MeTestUtils.runTest("Exec: add basic", testAddBasic),
    MeTestUtils.runTest("Exec: add multiple", testAddMultiple),
    MeTestUtils.runTest("Exec: add to nonexistent", testAddToNonexistent),
    MeTestUtils.runTest("Exec: add to string var", testAddToString),
    MeTestUtils.runTest("Exec: add no attributes", testAddNoAttributes),
    MeTestUtils.runTest("Exec: subtract basic", testSubtractBasic),
    MeTestUtils.runTest("Exec: subtract to negative", testSubtractToNegative),
    MeTestUtils.runTest("Exec: subtract from nonexistent", testSubtractFromNonexistent),
    MeTestUtils.runTest("Exec: ask stores placeholder", testAskStoresPlaceholder),
    MeTestUtils.runTest("Exec: ask without into", testAskNoInto),
    MeTestUtils.runTest("Exec: stop halts", testStopHalts),
    MeTestUtils.runTest("Exec: stop in repeat", testStopInRepeat),
    MeTestUtils.runTest("Exec: canvas execution", testCanvasExecution),
    MeTestUtils.runTest("Exec: canvas shape type", testCanvasShapeType),
    MeTestUtils.runTest("Exec: canvas empty", testCanvasEmpty),
    MeTestUtils.runTest("Exec: empty program", testEmptyProgramExecution)
  ];
}

export {
  testCreateEnvironment,
  testSaySimple,
  testSayMultiple,
  testSayEmpty,
  testSayWithInterpolation,
  testSayNoContent,
  testRememberString,
  testRememberNumber,
  testRememberOverwrite,
  testRememberNoName,
  testRememberNoContent,
  testAddBasic,
  testAddMultiple,
  testAddToNonexistent,
  testAddToString,
  testAddNoAttributes,
  testSubtractBasic,
  testSubtractToNegative,
  testSubtractFromNonexistent,
  testAskStoresPlaceholder,
  testAskNoInto,
  testStopHalts,
  testStopInRepeat,
  testCanvasExecution,
  testCanvasShapeType,
  testCanvasEmpty,
  testEmptyProgramExecution,
  run,
}
/* No side effect */
