// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeTestUtils from "./MeTestUtils.res.js";

function testEmptyProgram() {
  let node = MeTestUtils.program([]);
  if (MeTestUtils.assertEqual(node.nodeType, "Program", "empty program nodeType")) {
    return MeTestUtils.assertEqual(node.children, [], "empty program children");
  } else {
    return false;
  }
}

function testProgramWithChildren() {
  let node = MeTestUtils.program([
    MeTestUtils.say("Hello"),
    MeTestUtils.say("World")
  ]);
  let c = node.children;
  let len = c !== undefined ? c.length : 0;
  return MeTestUtils.assertEqual(len, 2, "program with two children");
}

function testSayNode() {
  let node = MeTestUtils.say("Hello!");
  if (MeTestUtils.assertEqual(node.nodeType, "Say", "say nodeType")) {
    return MeTestUtils.assertEqual(node.content, "Hello!", "say content");
  } else {
    return false;
  }
}

function testSayNodeNoAttributes() {
  let node = MeTestUtils.say("text");
  return MeTestUtils.assertEqual(node.attributes, undefined, "say has no attributes");
}

function testSayNodeNoChildren() {
  let node = MeTestUtils.say("text");
  return MeTestUtils.assertEqual(node.children, undefined, "say has no children");
}

function testRememberNode() {
  let node = MeTestUtils.remember("color", "blue");
  if (MeTestUtils.assertEqual(node.nodeType, "Remember", "remember nodeType")) {
    return MeTestUtils.assertEqual(node.content, "blue", "remember content");
  } else {
    return false;
  }
}

function testRememberNodeAttribute() {
  let node = MeTestUtils.remember("color", "blue");
  let attrs = node.attributes;
  let nameAttr = attrs !== undefined ? attrs["name"] : undefined;
  return MeTestUtils.assertEqual(nameAttr, "color", "remember name attribute");
}

function testAddNode() {
  let node = MeTestUtils.add("score", "10");
  if (MeTestUtils.assertEqual(node.nodeType, "Add", "add nodeType")) {
    return MeTestUtils.assertEqual(node.content, "10", "add content");
  } else {
    return false;
  }
}

function testAddNodeAttribute() {
  let node = MeTestUtils.add("score", "10");
  let attrs = node.attributes;
  let toAttr = attrs !== undefined ? attrs["to"] : undefined;
  return MeTestUtils.assertEqual(toAttr, "score", "add to attribute");
}

function testSubtractNode() {
  let node = MeTestUtils.subtract("lives", "1");
  if (MeTestUtils.assertEqual(node.nodeType, "Subtract", "subtract nodeType")) {
    return MeTestUtils.assertEqual(node.content, "1", "subtract content");
  } else {
    return false;
  }
}

function testSubtractNodeAttribute() {
  let node = MeTestUtils.subtract("lives", "1");
  let attrs = node.attributes;
  let fromAttr = attrs !== undefined ? attrs["from"] : undefined;
  return MeTestUtils.assertEqual(fromAttr, "lives", "subtract from attribute");
}

function testStopNode() {
  let node = MeTestUtils.stop();
  if (MeTestUtils.assertEqual(node.nodeType, "Stop", "stop nodeType") && MeTestUtils.assertEqual(node.children, undefined, "stop no children") && MeTestUtils.assertEqual(node.content, undefined, "stop no content")) {
    return MeTestUtils.assertEqual(node.attributes, undefined, "stop no attributes");
  } else {
    return false;
  }
}

function testAskNode() {
  let node = MeTestUtils.ask("answer", "What is your name?");
  if (MeTestUtils.assertEqual(node.nodeType, "Ask", "ask nodeType")) {
    return MeTestUtils.assertEqual(node.content, "What is your name?", "ask prompt");
  } else {
    return false;
  }
}

function testAskNodeAttribute() {
  let node = MeTestUtils.ask("answer", "prompt");
  let attrs = node.attributes;
  let intoAttr = attrs !== undefined ? attrs["into"] : undefined;
  return MeTestUtils.assertEqual(intoAttr, "answer", "ask into attribute");
}

function testRepeatNode() {
  let node = MeTestUtils.repeat(5, [MeTestUtils.say("hi")]);
  return MeTestUtils.assertEqual(node.nodeType, "Repeat", "repeat nodeType");
}

function testRepeatNodeTimesAttr() {
  let node = MeTestUtils.repeat(5, [MeTestUtils.say("hi")]);
  let attrs = node.attributes;
  let timesAttr = attrs !== undefined ? attrs["times"] : undefined;
  return MeTestUtils.assertEqual(timesAttr, "5", "repeat times attribute");
}

function testRepeatNodeChildren() {
  let node = MeTestUtils.repeat(3, [
    MeTestUtils.say("a"),
    MeTestUtils.say("b")
  ]);
  let c = node.children;
  let len = c !== undefined ? c.length : 0;
  return MeTestUtils.assertEqual(len, 2, "repeat children count");
}

function testChooseNode() {
  let node = MeTestUtils.choose([
    MeTestUtils.when_("x", "1", [MeTestUtils.say("one")]),
    MeTestUtils.otherwise([MeTestUtils.say("other")])
  ]);
  return MeTestUtils.assertEqual(node.nodeType, "Choose", "choose nodeType");
}

function testWhenNodeAttribute() {
  let node = MeTestUtils.when_("color", "red", [MeTestUtils.say("red!")]);
  let attrs = node.attributes;
  let condAttr = attrs !== undefined ? attrs["color-is"] : undefined;
  return MeTestUtils.assertEqual(condAttr, "red", "when color-is attribute");
}

function testWhenNotNodeAttribute() {
  let node = MeTestUtils.whenNot("color", "blue", [MeTestUtils.say("not blue")]);
  let attrs = node.attributes;
  let condAttr = attrs !== undefined ? attrs["color-is-not"] : undefined;
  return MeTestUtils.assertEqual(condAttr, "blue", "whenNot color-is-not attribute");
}

function testOtherwiseNode() {
  let node = MeTestUtils.otherwise([MeTestUtils.say("default")]);
  return MeTestUtils.assertEqual(node.nodeType, "Otherwise", "otherwise nodeType");
}

function testCanvasNode() {
  let node = MeTestUtils.canvas("400", "300", [MeTestUtils.shape("circle", [
      [
        "cx",
        "50"
      ],
      [
        "cy",
        "50"
      ],
      [
        "r",
        "25"
      ]
    ])]);
  return MeTestUtils.assertEqual(node.nodeType, "Canvas", "canvas nodeType");
}

function testCanvasAttributes() {
  let node = MeTestUtils.canvas("400", "300", []);
  let attrs = node.attributes;
  let wAttr = attrs !== undefined ? attrs["width"] : undefined;
  let attrs$1 = node.attributes;
  let hAttr = attrs$1 !== undefined ? attrs$1["height"] : undefined;
  if (MeTestUtils.assertEqual(wAttr, "400", "canvas width")) {
    return MeTestUtils.assertEqual(hAttr, "300", "canvas height");
  } else {
    return false;
  }
}

function testShapeNode() {
  let node = MeTestUtils.shape("rect", [
    [
      "x",
      "10"
    ],
    [
      "y",
      "20"
    ],
    [
      "w",
      "50"
    ],
    [
      "h",
      "30"
    ]
  ]);
  return MeTestUtils.assertEqual(node.nodeType, "Shape", "shape nodeType");
}

function testShapeTypeAttribute() {
  let node = MeTestUtils.shape("circle", [[
      "r",
      "10"
    ]]);
  let attrs = node.attributes;
  let tAttr = attrs !== undefined ? attrs["type"] : undefined;
  return MeTestUtils.assertEqual(tAttr, "circle", "shape type attribute");
}

function testMakeNodeDefaults() {
  let node = MeTestUtils.makeNode("Say", undefined, undefined, undefined, undefined);
  if (MeTestUtils.assertEqual(node.children, undefined, "makeNode default children") && MeTestUtils.assertEqual(node.attributes, undefined, "makeNode default attributes")) {
    return MeTestUtils.assertEqual(node.content, undefined, "makeNode default content");
  } else {
    return false;
  }
}

function run() {
  return [
    MeTestUtils.runTest("AST: empty program", testEmptyProgram),
    MeTestUtils.runTest("AST: program with children", testProgramWithChildren),
    MeTestUtils.runTest("AST: say node", testSayNode),
    MeTestUtils.runTest("AST: say no attributes", testSayNodeNoAttributes),
    MeTestUtils.runTest("AST: say no children", testSayNodeNoChildren),
    MeTestUtils.runTest("AST: remember node", testRememberNode),
    MeTestUtils.runTest("AST: remember name attribute", testRememberNodeAttribute),
    MeTestUtils.runTest("AST: add node", testAddNode),
    MeTestUtils.runTest("AST: add to attribute", testAddNodeAttribute),
    MeTestUtils.runTest("AST: subtract node", testSubtractNode),
    MeTestUtils.runTest("AST: subtract from attribute", testSubtractNodeAttribute),
    MeTestUtils.runTest("AST: stop node (self-closing)", testStopNode),
    MeTestUtils.runTest("AST: ask node", testAskNode),
    MeTestUtils.runTest("AST: ask into attribute", testAskNodeAttribute),
    MeTestUtils.runTest("AST: repeat node", testRepeatNode),
    MeTestUtils.runTest("AST: repeat times attribute", testRepeatNodeTimesAttr),
    MeTestUtils.runTest("AST: repeat children", testRepeatNodeChildren),
    MeTestUtils.runTest("AST: choose node", testChooseNode),
    MeTestUtils.runTest("AST: when attribute (var-is)", testWhenNodeAttribute),
    MeTestUtils.runTest("AST: whenNot attribute (var-is-not)", testWhenNotNodeAttribute),
    MeTestUtils.runTest("AST: otherwise node", testOtherwiseNode),
    MeTestUtils.runTest("AST: canvas node", testCanvasNode),
    MeTestUtils.runTest("AST: canvas attributes", testCanvasAttributes),
    MeTestUtils.runTest("AST: shape node", testShapeNode),
    MeTestUtils.runTest("AST: shape type attribute", testShapeTypeAttribute),
    MeTestUtils.runTest("AST: makeNode defaults", testMakeNodeDefaults)
  ];
}

export {
  testEmptyProgram,
  testProgramWithChildren,
  testSayNode,
  testSayNodeNoAttributes,
  testSayNodeNoChildren,
  testRememberNode,
  testRememberNodeAttribute,
  testAddNode,
  testAddNodeAttribute,
  testSubtractNode,
  testSubtractNodeAttribute,
  testStopNode,
  testAskNode,
  testAskNodeAttribute,
  testRepeatNode,
  testRepeatNodeTimesAttr,
  testRepeatNodeChildren,
  testChooseNode,
  testWhenNodeAttribute,
  testWhenNotNodeAttribute,
  testOtherwiseNode,
  testCanvasNode,
  testCanvasAttributes,
  testShapeNode,
  testShapeTypeAttribute,
  testMakeNodeDefaults,
  run,
}
/* No side effect */
