// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeTestUtils from "./MeTestUtils.res.js";
import * as MeTest_Parser from "./MeTest_Parser.res.js";
import * as MeTest_EdgeCases from "./MeTest_EdgeCases.res.js";
import * as MeTest_Execution from "./MeTest_Execution.res.js";
import * as MeTest_Repetition from "./MeTest_Repetition.res.js";
import * as MeTest_Conditionals from "./MeTest_Conditionals.res.js";
import * as MeTest_ASTConstruction from "./MeTest_ASTConstruction.res.js";
import * as MeTest_ValueAndInterpolation from "./MeTest_ValueAndInterpolation.res.js";

console.log("=== Me Language Test Suite ===\n");

let allResults = MeTest_ValueAndInterpolation.run().concat(MeTest_ASTConstruction.run()).concat(MeTest_Execution.run()).concat(MeTest_Conditionals.run()).concat(MeTest_Repetition.run()).concat(MeTest_EdgeCases.run()).concat(MeTest_Parser.run());

let exitCode = MeTestUtils.summarise(allResults);

if (exitCode !== 0) {
  console.error("\nSome tests failed.");
} else {
  console.log("\nAll tests passed.");
}

/*  Not a pure module */
