// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeParser from "../src/MeParser.res.js";
import * as MeTestUtils from "./MeTestUtils.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function parseOk(source) {
  let node = MeParser.parse(source);
  if (node.TAG === "Ok") {
    return node._0;
  }
}

function parseErr(source) {
  let match = MeParser.parse(source);
  return match.TAG !== "Ok";
}

function testEmptyString() {
  let node = parseOk("");
  if (node !== undefined && MeTestUtils.assertEqual(node.nodeType, "Program", "empty string -> Program")) {
    return MeTestUtils.assertEqual(node.children, [], "empty string -> no children");
  } else {
    return false;
  }
}

function testWhitespaceOnly() {
  let node = parseOk("   \n\t  ");
  if (node !== undefined) {
    return MeTestUtils.assertEqual(node.children, [], "whitespace -> no children");
  } else {
    return false;
  }
}

function testParseSay() {
  let prog = parseOk("<say>Hello, world!</say>");
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  if (!MeTestUtils.assertEqual(kids.length, 1, "say: one child")) {
    return false;
  }
  let child = kids[0];
  if (MeTestUtils.assertEqual(child.nodeType, "Say", "say: nodeType")) {
    return MeTestUtils.assertEqual(child.content, "Hello, world!", "say: content");
  } else {
    return false;
  }
}

function testParseSayInterpolation() {
  let prog = parseOk("<say>Hello {name}!</say>");
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  return MeTestUtils.assertEqual(child.content, "Hello {name}!", "say: preserves interpolation");
}

function testParseSayEmpty() {
  let prog = parseOk("<say></say>");
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  return MeTestUtils.assertEqual(child.content, "", "say: empty content");
}

function testParseRemember() {
  let prog = parseOk(`<remember name="color">blue</remember>`);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  if (!(MeTestUtils.assertEqual(child.nodeType, "Remember", "remember: nodeType") && MeTestUtils.assertEqual(child.content, "blue", "remember: content"))) {
    return false;
  }
  let attrs = child.attributes;
  let nameAttr = attrs !== undefined ? attrs["name"] : undefined;
  return MeTestUtils.assertEqual(nameAttr, "color", "remember: name attribute");
}

function testParseAsk() {
  let prog = parseOk(`<ask into="answer">What is your name?</ask>`);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  if (!(MeTestUtils.assertEqual(child.nodeType, "Ask", "ask: nodeType") && MeTestUtils.assertEqual(child.content, "What is your name?", "ask: prompt"))) {
    return false;
  }
  let attrs = child.attributes;
  let intoAttr = attrs !== undefined ? attrs["into"] : undefined;
  return MeTestUtils.assertEqual(intoAttr, "answer", "ask: into attribute");
}

function testParseAdd() {
  let prog = parseOk(`<add to="score">10</add>`);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  if (!(MeTestUtils.assertEqual(child.nodeType, "Add", "add: nodeType") && MeTestUtils.assertEqual(child.content, "10", "add: amount"))) {
    return false;
  }
  let attrs = child.attributes;
  let toAttr = attrs !== undefined ? attrs["to"] : undefined;
  return MeTestUtils.assertEqual(toAttr, "score", "add: to attribute");
}

function testParseSubtract() {
  let prog = parseOk(`<subtract from="lives">1</subtract>`);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  if (!(MeTestUtils.assertEqual(child.nodeType, "Subtract", "subtract: nodeType") && MeTestUtils.assertEqual(child.content, "1", "subtract: amount"))) {
    return false;
  }
  let attrs = child.attributes;
  let fromAttr = attrs !== undefined ? attrs["from"] : undefined;
  return MeTestUtils.assertEqual(fromAttr, "lives", "subtract: from attribute");
}

function testParseStop() {
  let prog = parseOk("<stop/>");
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  if (MeTestUtils.assertEqual(child.nodeType, "Stop", "stop: nodeType") && MeTestUtils.assertEqual(child.children, undefined, "stop: no children")) {
    return MeTestUtils.assertEqual(child.content, undefined, "stop: no content");
  } else {
    return false;
  }
}

function testParseStopWithSpaces() {
  let prog = parseOk("<stop />");
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  return MeTestUtils.assertEqual(child.nodeType, "Stop", "stop with space: nodeType");
}

function testParseRepeat() {
  let prog = parseOk(`<repeat times="3"><say>Hip hip hooray!</say></repeat>`);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let rep = kids[0];
  if (!MeTestUtils.assertEqual(rep.nodeType, "Repeat", "repeat: nodeType")) {
    return false;
  }
  let attrs = rep.attributes;
  let timesAttr = attrs !== undefined ? attrs["times"] : undefined;
  if (!MeTestUtils.assertEqual(timesAttr, "3", "repeat: times attribute")) {
    return false;
  }
  let repKids = Core__Option.getOr(rep.children, []);
  if (!MeTestUtils.assertEqual(repKids.length, 1, "repeat: one child")) {
    return false;
  }
  let child = repKids[0];
  if (MeTestUtils.assertEqual(child.nodeType, "Say", "repeat child: Say")) {
    return MeTestUtils.assertEqual(child.content, "Hip hip hooray!", "repeat child: content");
  } else {
    return false;
  }
}

function testParseChoose() {
  let prog = parseOk(`
    <choose>
      <when weather-is="sunny">
        <say>Go outside!</say>
      </when>
      <when weather-is="rainy">
        <say>Stay inside!</say>
      </when>
      <otherwise>
        <say>Check the weather!</say>
      </otherwise>
    </choose>
  `);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let choose = kids[0];
  if (!MeTestUtils.assertEqual(choose.nodeType, "Choose", "choose: nodeType")) {
    return false;
  }
  let chooseKids = Core__Option.getOr(choose.children, []);
  if (!MeTestUtils.assertEqual(chooseKids.length, 3, "choose: 3 branches")) {
    return false;
  }
  let when1 = chooseKids[0];
  let tmp = false;
  if (MeTestUtils.assertEqual(when1.nodeType, "When", "when1: nodeType")) {
    let attrs = when1.attributes;
    let condAttr = attrs !== undefined ? attrs["weather-is"] : undefined;
    tmp = MeTestUtils.assertEqual(condAttr, "sunny", "when1: weather-is attribute");
  }
  if (!tmp) {
    return false;
  }
  let otherwise = chooseKids[2];
  return MeTestUtils.assertEqual(otherwise.nodeType, "Otherwise", "otherwise: nodeType");
}

function testParseCanvas() {
  let prog = parseOk(`
    <canvas width="400" height="300">
      <shape type="circle" cx="50" cy="50" r="25" />
      <shape type="rect" x="100" y="100" w="50" h="30"/>
    </canvas>
  `);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let canvas = kids[0];
  if (!MeTestUtils.assertEqual(canvas.nodeType, "Canvas", "canvas: nodeType")) {
    return false;
  }
  let attrs = canvas.attributes;
  let wAttr = attrs !== undefined ? attrs["width"] : undefined;
  if (!MeTestUtils.assertEqual(wAttr, "400", "canvas: width")) {
    return false;
  }
  let canvasKids = Core__Option.getOr(canvas.children, []);
  if (!MeTestUtils.assertEqual(canvasKids.length, 2, "canvas: 2 shapes")) {
    return false;
  }
  let shape1 = canvasKids[0];
  if (!MeTestUtils.assertEqual(shape1.nodeType, "Shape", "shape1: nodeType")) {
    return false;
  }
  let attrs$1 = shape1.attributes;
  let typeAttr = attrs$1 !== undefined ? attrs$1["type"] : undefined;
  return MeTestUtils.assertEqual(typeAttr, "circle", "shape1: type");
}

function testParseMultiNode() {
  let prog = parseOk(`
    <remember name="name">Alex</remember>
    <remember name="age">10</remember>
    <say>My name is {name} and I am {age} years old!</say>
  `);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  if (!MeTestUtils.assertEqual(kids.length, 3, "multi: 3 children")) {
    return false;
  }
  let r1 = kids[0];
  let r2 = kids[1];
  let s = kids[2];
  if (MeTestUtils.assertEqual(r1.nodeType, "Remember", "multi child 0: Remember") && MeTestUtils.assertEqual(r2.nodeType, "Remember", "multi child 1: Remember")) {
    return MeTestUtils.assertEqual(s.nodeType, "Say", "multi child 2: Say");
  } else {
    return false;
  }
}

function testParseCountingProgram() {
  let prog = parseOk(`
    <say>Let's count some sheep!</say>
    <remember name="sheep">0</remember>
    <repeat times="5">
      <add to="sheep">1</add>
      <say>{sheep} sheep jumping over the fence!</say>
    </repeat>
    <say>I counted {sheep} sheep! Time for sleep!</say>
  `);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  if (!MeTestUtils.assertEqual(kids.length, 4, "counting: 4 top-level nodes")) {
    return false;
  }
  let rep = kids[2];
  if (!MeTestUtils.assertEqual(rep.nodeType, "Repeat", "counting: repeat node")) {
    return false;
  }
  let repKids = Core__Option.getOr(rep.children, []);
  return MeTestUtils.assertEqual(repKids.length, 2, "counting: 2 children in repeat");
}

function testParseComments() {
  let prog = parseOk(`
    <!-- This is a comment -->
    <say>Hello!</say>
    <!-- Another comment -->
  `);
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  if (!MeTestUtils.assertEqual(kids.length, 1, "comments: only 1 real node")) {
    return false;
  }
  let child = kids[0];
  return MeTestUtils.assertEqual(child.content, "Hello!", "comments: correct content");
}

function testParseSingleQuotedAttr() {
  let prog = parseOk("<remember name='color'>blue</remember>");
  if (prog === undefined) {
    return false;
  }
  let kids = Core__Option.getOr(prog.children, []);
  let child = kids[0];
  let attrs = child.attributes;
  let nameAttr = attrs !== undefined ? attrs["name"] : undefined;
  return MeTestUtils.assertEqual(nameAttr, "color", "single-quoted attribute");
}

function testErrorUnknownTag() {
  return parseErr("<shout>Hello!</shout>");
}

function testErrorUnclosedTag() {
  return parseErr("<say>Hello!");
}

function testErrorMismatchedClose() {
  return parseErr("<say>Hello!</remember>");
}

function testErrorTextOutsideTag() {
  return parseErr("Hello world");
}

function testErrorUnclosedAttribute() {
  return parseErr(`<remember name="color>blue</remember>`);
}

function testParseAndExecuteSay() {
  let prog = MeParser.parse("<say>Round trip works!</say>");
  if (prog.TAG !== "Ok") {
    return false;
  }
  let env = MeTestUtils.runProgram(prog._0);
  return MeTestUtils.assertEqual(env.output, ["Round trip works!"], "parse+execute: say output");
}

function testParseAndExecuteRememberSay() {
  let prog = MeParser.parse(`
    <remember name="pet">cat</remember>
    <say>I have a {pet}!</say>
  `);
  if (prog.TAG !== "Ok") {
    return false;
  }
  let env = MeTestUtils.runProgram(prog._0);
  return MeTestUtils.assertEqual(env.output, ["I have a cat!"], "parse+execute: interpolation");
}

function testParseAndExecuteRepeat() {
  let prog = MeParser.parse(`
    <repeat times="3">
      <say>Go!</say>
    </repeat>
  `);
  if (prog.TAG !== "Ok") {
    return false;
  }
  let env = MeTestUtils.runProgram(prog._0);
  return MeTestUtils.assertEqual(env.output, [
    "Go!",
    "Go!",
    "Go!"
  ], "parse+execute: repeat 3x");
}

function run() {
  return [
    MeTestUtils.runTest("Parser: empty string", testEmptyString),
    MeTestUtils.runTest("Parser: whitespace only", testWhitespaceOnly),
    MeTestUtils.runTest("Parser: <say> basic", testParseSay),
    MeTestUtils.runTest("Parser: <say> with interpolation", testParseSayInterpolation),
    MeTestUtils.runTest("Parser: <say> empty content", testParseSayEmpty),
    MeTestUtils.runTest("Parser: <remember>", testParseRemember),
    MeTestUtils.runTest("Parser: <ask>", testParseAsk),
    MeTestUtils.runTest("Parser: <add>", testParseAdd),
    MeTestUtils.runTest("Parser: <subtract>", testParseSubtract),
    MeTestUtils.runTest("Parser: <stop/>", testParseStop),
    MeTestUtils.runTest("Parser: <stop /> with space", testParseStopWithSpaces),
    MeTestUtils.runTest("Parser: <repeat>", testParseRepeat),
    MeTestUtils.runTest("Parser: <choose>/<when>/<otherwise>", testParseChoose),
    MeTestUtils.runTest("Parser: <canvas>/<shape>", testParseCanvas),
    MeTestUtils.runTest("Parser: multiple top-level nodes", testParseMultiNode),
    MeTestUtils.runTest("Parser: full counting program", testParseCountingProgram),
    MeTestUtils.runTest("Parser: comments are skipped", testParseComments),
    MeTestUtils.runTest("Parser: single-quoted attributes", testParseSingleQuotedAttr),
    MeTestUtils.runTest("Parser: error on unknown tag", testErrorUnknownTag),
    MeTestUtils.runTest("Parser: error on unclosed tag", testErrorUnclosedTag),
    MeTestUtils.runTest("Parser: error on mismatched close", testErrorMismatchedClose),
    MeTestUtils.runTest("Parser: error on text outside tag", testErrorTextOutsideTag),
    MeTestUtils.runTest("Parser: error on unclosed attribute", testErrorUnclosedAttribute),
    MeTestUtils.runTest("Parser: parse+execute <say>", testParseAndExecuteSay),
    MeTestUtils.runTest("Parser: parse+execute remember+say", testParseAndExecuteRememberSay),
    MeTestUtils.runTest("Parser: parse+execute <repeat>", testParseAndExecuteRepeat)
  ];
}

export {
  parseOk,
  parseErr,
  testEmptyString,
  testWhitespaceOnly,
  testParseSay,
  testParseSayInterpolation,
  testParseSayEmpty,
  testParseRemember,
  testParseAsk,
  testParseAdd,
  testParseSubtract,
  testParseStop,
  testParseStopWithSpaces,
  testParseRepeat,
  testParseChoose,
  testParseCanvas,
  testParseMultiNode,
  testParseCountingProgram,
  testParseComments,
  testParseSingleQuotedAttr,
  testErrorUnknownTag,
  testErrorUnclosedTag,
  testErrorMismatchedClose,
  testErrorTextOutsideTag,
  testErrorUnclosedAttribute,
  testParseAndExecuteSay,
  testParseAndExecuteRememberSay,
  testParseAndExecuteRepeat,
  run,
}
/* No side effect */
