// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MeLanguage from "./MeLanguage.res.js";

function main() {
  MeLanguage.demonstrateMeLanguage();
}

let createMeEnvironment = MeLanguage.createMeEnvironment;

let valueToString = MeLanguage.valueToString;

let parseValue = MeLanguage.parseValue;

let interpolate = MeLanguage.interpolate;

let execute = MeLanguage.execute;

let executeChoose = MeLanguage.executeChoose;

let checkWhenCondition = MeLanguage.checkWhenCondition;

let demonstrateMeLanguage = MeLanguage.demonstrateMeLanguage;

export {
  createMeEnvironment,
  valueToString,
  parseValue,
  interpolate,
  execute,
  executeChoose,
  checkWhenCondition,
  demonstrateMeLanguage,
  main,
}
/* No side effect */
