// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function nodeTypeToString(nt) {
  switch (nt) {
    case "Program" :
      return "Program";
    case "Say" :
      return "Say";
    case "Remember" :
      return "Remember";
    case "Ask" :
      return "Ask";
    case "Choose" :
      return "Choose";
    case "When" :
      return "When";
    case "Otherwise" :
      return "Otherwise";
    case "Repeat" :
      return "Repeat";
    case "Canvas" :
      return "Canvas";
    case "Shape" :
      return "Shape";
    case "Add" :
      return "Add";
    case "Subtract" :
      return "Subtract";
    case "Stop" :
      return "Stop";
  }
}

function nodeToJsonObj(node) {
  let obj = {};
  obj["nodeType"] = nodeTypeToString(node.nodeType);
  let c = node.content;
  if (c !== undefined) {
    obj["content"] = c;
  } else {
    obj["content"] = null;
  }
  let attrs = node.attributes;
  if (attrs !== undefined) {
    let attrObj = {};
    Object.entries(attrs).forEach(param => {
      attrObj[param[0]] = param[1];
    });
    obj["attributes"] = attrObj;
  } else {
    obj["attributes"] = null;
  }
  let kids = node.children;
  if (kids !== undefined) {
    let childArr = kids.map(nodeToJsonObj);
    obj["children"] = childArr;
  } else {
    obj["children"] = null;
  }
  return obj;
}

function toJson(node) {
  let obj = nodeToJsonObj(node);
  return Core__Option.getOr(JSON.stringify(obj, null, 2), "{}");
}

function escapeString(s) {
  let escaped = s.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n").replaceAll("\r", "\\r").replaceAll("\t", "\\t");
  return `"` + escaped + `"`;
}

function indent(depth) {
  let buf = "";
  for (let _for = 0; _for < depth; ++_for) {
    buf = buf + "  ";
  }
  return buf;
}

function nodeToSexpr(node, depth) {
  let pad = indent(depth);
  let tag = nodeTypeToString(node.nodeType);
  let attrs = node.attributes;
  let attrFragments = attrs !== undefined ? Object.entries(attrs).map(param => `:` + param[0] + ` ` + escapeString(param[1])) : [];
  let c = node.content;
  let contentFragment = c !== undefined ? [`:content ` + escapeString(c)] : [];
  let allFragments = attrFragments.concat(contentFragment);
  let kids = node.children;
  if (kids !== undefined && kids.length > 0) {
    let fragStr = allFragments.length > 0 ? " " + allFragments.join(" ") : "";
    let childLines = kids.map(child => nodeToSexpr(child, depth + 1 | 0)).join("\n");
    return pad + `(` + tag + fragStr + `\n` + childLines + `)`;
  }
  let fragStr$1 = allFragments.length > 0 ? " " + allFragments.join(" ") : "";
  return pad + `(` + tag + fragStr$1 + `)`;
}

function toSexpr(node) {
  return nodeToSexpr(node, 0);
}

function parseFormat(s) {
  let match = s.toLowerCase();
  switch (match) {
    case "json" :
      return "Json";
    case "s-expr" :
    case "sexp" :
    case "sexpr" :
      return "Sexpr";
    default:
      return;
  }
}

function dump(node, format) {
  if (format === "Json") {
    return toJson(node);
  } else {
    return nodeToSexpr(node, 0);
  }
}

export {
  nodeTypeToString,
  nodeToJsonObj,
  toJson,
  escapeString,
  indent,
  nodeToSexpr,
  toSexpr,
  parseFormat,
  dump,
}
/* No side effect */
