// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.js";
import * as Core__Float from "@rescript/core/src/Core__Float.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function createMeEnvironment() {
  return {
    variables: {},
    output: [],
    canvas: [],
    stopped: false
  };
}

function valueToString(value) {
  if (value.TAG === "String") {
    return value._0;
  } else {
    return value._0.toString();
  }
}

function parseValue(s) {
  let n = Core__Float.fromString(s);
  if (n !== undefined) {
    return {
      TAG: "Number",
      _0: n
    };
  } else {
    return {
      TAG: "String",
      _0: s
    };
  }
}

function interpolate(text, env) {
  let re = /\{([^}]+)\}/g;
  return text.replace(re, (match, param, param$1) => {
    let varName = match.slice(1, -1).trim();
    let value = env.variables[varName];
    if (value !== undefined) {
      return valueToString(value);
    } else {
      return match;
    }
  });
}

function execute(node, env) {
  if (env.stopped) {
    return;
  }
  let match = node.nodeType;
  switch (match) {
    case "Program" :
      Core__Option.getOr(node.children, []).forEach(child => {
        if (!env.stopped) {
          return execute(child, env);
        }
      });
      return;
    case "Say" :
      let content = node.content;
      if (content === undefined) {
        return;
      }
      let message = interpolate(content, env);
      env.output = env.output.concat([message]);
      console.log(message);
      return;
    case "Remember" :
      let name = Core__Option.flatMap(node.attributes, attrs => attrs["name"]);
      let value = node.content;
      if (name !== undefined && value !== undefined) {
        env.variables[name] = parseValue(value);
        return;
      } else {
        return;
      }
    case "Ask" :
      let varName = Core__Option.flatMap(node.attributes, attrs => attrs["into"]);
      let prompt = Core__Option.getOr(node.content, "Enter a value:");
      if (varName !== undefined) {
        console.log("[Ask] " + interpolate(prompt, env));
        env.variables[varName] = {
          TAG: "String",
          _0: "user-input"
        };
        return;
      } else {
        return;
      }
    case "Choose" :
      return executeChoose(node, env);
    case "Repeat" :
      let times = Core__Option.flatMap(node.attributes, attrs => attrs["times"]);
      if (times === undefined) {
        return;
      }
      let count = Core__Int.fromString(times, undefined);
      if (count === undefined) {
        return;
      }
      for (let _for = 0; _for < count; ++_for) {
        if (!env.stopped) {
          Core__Option.getOr(node.children, []).forEach(child => execute(child, env));
        }
      }
      return;
    case "Canvas" :
      let width = Core__Option.getOr(Core__Option.flatMap(node.attributes, attrs => attrs["width"]), "0");
      let height = Core__Option.getOr(Core__Option.flatMap(node.attributes, attrs => attrs["height"]), "0");
      console.log("[Canvas] Creating " + width + "x" + height + " canvas");
      Core__Option.getOr(node.children, []).forEach(child => {
        let match = child.nodeType;
        if (match !== "Shape") {
          return;
        }
        let shapeType = Core__Option.getOr(Core__Option.flatMap(child.attributes, attrs => attrs["type"]), "unknown");
        let props = Core__Option.getOr(child.attributes, {});
        env.canvas = env.canvas.concat([{
            shape: shapeType,
            props: props
          }]);
        console.log("[Canvas] Drawing " + shapeType);
      });
      return;
    case "When" :
    case "Otherwise" :
    case "Shape" :
      return;
    case "Add" :
      let varName$1 = Core__Option.flatMap(node.attributes, attrs => attrs["to"]);
      let amount = node.content;
      if (varName$1 === undefined) {
        return;
      }
      if (amount === undefined) {
        return;
      }
      let match$1 = env.variables[varName$1];
      let match$2 = Core__Float.fromString(amount);
      if (match$1 !== undefined && match$1.TAG !== "String" && match$2 !== undefined) {
        env.variables[varName$1] = {
          TAG: "Number",
          _0: match$1._0 + match$2
        };
        return;
      } else {
        return;
      }
    case "Subtract" :
      let varName$2 = Core__Option.flatMap(node.attributes, attrs => attrs["from"]);
      let amount$1 = node.content;
      if (varName$2 === undefined) {
        return;
      }
      if (amount$1 === undefined) {
        return;
      }
      let match$3 = env.variables[varName$2];
      let match$4 = Core__Float.fromString(amount$1);
      if (match$3 !== undefined && match$3.TAG !== "String" && match$4 !== undefined) {
        env.variables[varName$2] = {
          TAG: "Number",
          _0: match$3._0 - match$4
        };
        return;
      } else {
        return;
      }
    case "Stop" :
      env.stopped = true;
      return;
  }
}

function executeChoose(node, env) {
  let children = Core__Option.getOr(node.children, []);
  let _remaining = children;
  while (true) {
    let remaining = _remaining;
    let child = remaining[0];
    if (child === undefined) {
      return;
    }
    let match = child.nodeType;
    switch (match) {
      case "When" :
        let conditionMet = checkWhenCondition(child, env);
        if (conditionMet) {
          Core__Option.getOr(child.children, []).forEach(whenChild => execute(whenChild, env));
          return;
        }
        _remaining = remaining.slice(1);
        continue;
      case "Otherwise" :
        Core__Option.getOr(child.children, []).forEach(otherwiseChild => execute(otherwiseChild, env));
        return;
      default:
        _remaining = remaining.slice(1);
        continue;
    }
  };
}

function checkWhenCondition(node, env) {
  let attrs = node.attributes;
  if (attrs !== undefined) {
    return Object.entries(attrs).some(param => {
      let expectedValue = param[1];
      let key = param[0];
      if (key.endsWith("-is")) {
        let varName = key.slice(0, -3);
        let actualValue = env.variables[varName];
        if (actualValue !== undefined) {
          return valueToString(actualValue) === expectedValue;
        } else {
          return false;
        }
      }
      if (!key.endsWith("-is-not")) {
        return false;
      }
      let varName$1 = key.slice(0, -7);
      let actualValue$1 = env.variables[varName$1];
      if (actualValue$1 !== undefined) {
        return valueToString(actualValue$1) !== expectedValue;
      } else {
        return true;
      }
    });
  } else {
    return false;
  }
}

function demonstrateMeLanguage() {
  console.log("=== Me Language Demo ===\n");
  console.log("Me is a programming language for children ages 8-12.\n");
  console.log("Example 1: Hello World");
  let helloProgram_children = [{
      nodeType: "Say",
      children: undefined,
      attributes: undefined,
      content: "Hello! I am learning to code!"
    }];
  let helloProgram = {
    nodeType: "Program",
    children: helloProgram_children,
    attributes: undefined,
    content: undefined
  };
  execute(helloProgram, {
    variables: {},
    output: [],
    canvas: [],
    stopped: false
  });
  console.log("");
  console.log("Example 2: Remembering Things");
  let nameAttrs = {};
  nameAttrs["name"] = "my-name";
  let ageAttrs = {};
  ageAttrs["name"] = "my-age";
  let variablesProgram_children = [
    {
      nodeType: "Remember",
      children: undefined,
      attributes: nameAttrs,
      content: "Alex"
    },
    {
      nodeType: "Remember",
      children: undefined,
      attributes: ageAttrs,
      content: "10"
    },
    {
      nodeType: "Say",
      children: undefined,
      attributes: undefined,
      content: "My name is {my-name} and I am {my-age} years old!"
    }
  ];
  let variablesProgram = {
    nodeType: "Program",
    children: variablesProgram_children,
    attributes: undefined,
    content: undefined
  };
  execute(variablesProgram, {
    variables: {},
    output: [],
    canvas: [],
    stopped: false
  });
  console.log("");
  console.log("Example 3: Making Choices");
  let weatherAttrs = {};
  weatherAttrs["name"] = "weather";
  let sunnyAttrs = {};
  sunnyAttrs["weather-is"] = "sunny";
  let rainyAttrs = {};
  rainyAttrs["weather-is"] = "rainy";
  let choicesProgram_children = [
    {
      nodeType: "Remember",
      children: undefined,
      attributes: weatherAttrs,
      content: "sunny"
    },
    {
      nodeType: "Choose",
      children: [
        {
          nodeType: "When",
          children: [{
              nodeType: "Say",
              children: undefined,
              attributes: undefined,
              content: "Let's go outside!"
            }],
          attributes: sunnyAttrs,
          content: undefined
        },
        {
          nodeType: "When",
          children: [{
              nodeType: "Say",
              children: undefined,
              attributes: undefined,
              content: "Let's read a book!"
            }],
          attributes: rainyAttrs,
          content: undefined
        },
        {
          nodeType: "Otherwise",
          children: [{
              nodeType: "Say",
              children: undefined,
              attributes: undefined,
              content: "What's the weather like?"
            }],
          attributes: undefined,
          content: undefined
        }
      ],
      attributes: undefined,
      content: undefined
    }
  ];
  let choicesProgram = {
    nodeType: "Program",
    children: choicesProgram_children,
    attributes: undefined,
    content: undefined
  };
  execute(choicesProgram, {
    variables: {},
    output: [],
    canvas: [],
    stopped: false
  });
  console.log("");
  console.log("Example 4: Repeating Things");
  let repeatAttrs = {};
  repeatAttrs["times"] = "3";
  let repeatProgram_children = [{
      nodeType: "Repeat",
      children: [{
          nodeType: "Say",
          children: undefined,
          attributes: undefined,
          content: "Hip hip hooray!"
        }],
      attributes: repeatAttrs,
      content: undefined
    }];
  let repeatProgram = {
    nodeType: "Program",
    children: repeatProgram_children,
    attributes: undefined,
    content: undefined
  };
  execute(repeatProgram, {
    variables: {},
    output: [],
    canvas: [],
    stopped: false
  });
  console.log("");
  console.log("Example 5: Counting");
  let scoreAttrs = {};
  scoreAttrs["name"] = "score";
  let addAttrs = {};
  addAttrs["to"] = "score";
  let countRepeatAttrs = {};
  countRepeatAttrs["times"] = "3";
  let countingProgram_children = [
    {
      nodeType: "Remember",
      children: undefined,
      attributes: scoreAttrs,
      content: "0"
    },
    {
      nodeType: "Repeat",
      children: [
        {
          nodeType: "Add",
          children: undefined,
          attributes: addAttrs,
          content: "10"
        },
        {
          nodeType: "Say",
          children: undefined,
          attributes: undefined,
          content: "Score is now: {score}"
        }
      ],
      attributes: countRepeatAttrs,
      content: undefined
    }
  ];
  let countingProgram = {
    nodeType: "Program",
    children: countingProgram_children,
    attributes: undefined,
    content: undefined
  };
  execute(countingProgram, {
    variables: {},
    output: [],
    canvas: [],
    stopped: false
  });
  console.log("");
  console.log("=== Demo Complete ===");
  console.log("\nMe makes programming fun and approachable for kids!");
}

export {
  createMeEnvironment,
  valueToString,
  parseValue,
  interpolate,
  execute,
  executeChoose,
  checkWhenCondition,
  demonstrateMeLanguage,
}
/* No side effect */
