// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as RescriptCore from "@rescript/core/src/RescriptCore.res.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function makeState(source) {
  return {
    source: source,
    pos: 0
  };
}

function isAtEnd(state) {
  return state.pos >= state.source.length;
}

function peek(state) {
  if (isAtEnd(state)) {
    return;
  } else {
    return state.source.charAt(state.pos);
  }
}

function advance(state, n) {
  state.pos = state.pos + n | 0;
}

function startsWith(state, prefix) {
  let remaining = state.source.slice(state.pos);
  return remaining.startsWith(prefix);
}

function skipWhitespace(state) {
  let len = state.source.length;
  let $$continue = true;
  while ($$continue && state.pos < len) {
    let ch = state.source.charAt(state.pos);
    if (ch === " " || ch === "\t" || ch === "\n" || ch === "\r") {
      state.pos = state.pos + 1 | 0;
    } else {
      $$continue = false;
    }
  };
}

function skipComment(state) {
  if (!startsWith(state, "<!--")) {
    return;
  }
  advance(state, 4);
  let len = state.source.length;
  let found = false;
  while (!found && state.pos < (len - 2 | 0)) {
    if (state.source.charAt(state.pos) === "-" && state.source.charAt(state.pos + 1 | 0) === "-" && state.source.charAt(state.pos + 2 | 0) === ">") {
      advance(state, 3);
      found = true;
    } else {
      advance(state, 1);
    }
  };
  if (!found) {
    state.pos = len;
    return;
  }
}

function skipWhitespaceAndComments(state) {
  let changed = true;
  while (changed) {
    let before = state.pos;
    skipWhitespace(state);
    if (startsWith(state, "<!--")) {
      skipComment(state);
    }
    changed = state.pos !== before;
  };
}

function tagNameToNodeType(tagName) {
  let match = tagName.toLowerCase();
  switch (match) {
    case "add" :
      return "Add";
    case "ask" :
      return "Ask";
    case "canvas" :
      return "Canvas";
    case "choose" :
      return "Choose";
    case "otherwise" :
      return "Otherwise";
    case "remember" :
      return "Remember";
    case "repeat" :
      return "Repeat";
    case "say" :
      return "Say";
    case "shape" :
      return "Shape";
    case "stop" :
      return "Stop";
    case "subtract" :
      return "Subtract";
    case "when" :
      return "When";
    default:
      return;
  }
}

function isSelfClosingTag(tagName) {
  let match = tagName.toLowerCase();
  switch (match) {
    case "shape" :
    case "stop" :
      return true;
    default:
      return false;
  }
}

function isContainerTag(tagName) {
  let match = tagName.toLowerCase();
  switch (match) {
    case "canvas" :
    case "choose" :
    case "otherwise" :
    case "repeat" :
    case "when" :
      return true;
    default:
      return false;
  }
}

function parseQuotedValue(state, quoteChar) {
  let buf = "";
  let len = state.source.length;
  let found = false;
  while (!found && state.pos < len) {
    let ch = state.source.charAt(state.pos);
    if (ch === quoteChar) {
      advance(state, 1);
      found = true;
    } else {
      buf = buf + ch;
      advance(state, 1);
    }
  };
  if (found) {
    return {
      TAG: "Ok",
      _0: buf
    };
  } else {
    return {
      TAG: "Error",
      _0: `Oops! I found an attribute value that starts with ` + quoteChar + ` but never ends. ` + (`Make sure to close it with another ` + quoteChar + `.`)
    };
  }
}

function parseAttrName(state) {
  let buf = "";
  let len = state.source.length;
  let $$continue = true;
  while ($$continue && state.pos < len) {
    let ch = state.source.charAt(state.pos);
    let code = state.source.charCodeAt(state.pos);
    if (code >= 97.0 && code <= 122.0 || code >= 65.0 && code <= 90.0 || code >= 48.0 && code <= 57.0 || ch === "-" || ch === "_") {
      buf = buf + ch;
      advance(state, 1);
    } else {
      $$continue = false;
    }
  };
  return buf;
}

function parseAttributes(state) {
  let attrs = {};
  let error;
  let done = false;
  while (!done && error === undefined) {
    skipWhitespace(state);
    if (isAtEnd(state)) {
      done = true;
    } else {
      let ch = Core__Option.getOr(peek(state), "");
      if (ch === ">" || ch === "/") {
        done = true;
      } else {
        let name = parseAttrName(state);
        if (name === "") {
          let badChar = Core__Option.getOr(peek(state), "end of file");
          error = `Hmm, I found something unexpected (` + badChar + `) inside a tag. Attribute names should use letters, numbers, and hyphens.`;
        } else {
          skipWhitespace(state);
          if (Primitive_object.equal(peek(state), "=")) {
            advance(state, 1);
            skipWhitespace(state);
            let quoteChar = Core__Option.getOr(peek(state), "");
            if (quoteChar === "\"" || quoteChar === "'") {
              advance(state, 1);
              let value = parseQuotedValue(state, quoteChar);
              if (value.TAG === "Ok") {
                attrs[name] = value._0;
              } else {
                error = value._0;
              }
            } else {
              error = `The attribute "` + name + `" needs its value in quotes. ` + (`Try: ` + name + `="value"`);
            }
          } else {
            attrs[name] = "";
          }
        }
      }
    }
  };
  let e = error;
  if (e !== undefined) {
    return {
      TAG: "Error",
      _0: e
    };
  } else {
    return {
      TAG: "Ok",
      _0: attrs
    };
  }
}

function parseTextContent(state) {
  let buf = "";
  let len = state.source.length;
  while (state.pos < len && state.source.charAt(state.pos) !== "<") {
    buf = buf + state.source.charAt(state.pos);
    advance(state, 1);
  };
  return buf.trim();
}

function parseOpenTag(state) {
  if (Primitive_object.notequal(peek(state), "<")) {
    return {
      TAG: "Error",
      _0: `I expected a tag to start with < but found something else. All Me commands start with < like <say> or <remember>.`
    };
  }
  advance(state, 1);
  if (Primitive_object.equal(peek(state), "/")) {
    return {
      TAG: "Error",
      _0: `I found a closing tag where I expected an opening tag.`
    };
  }
  let tagName = parseAttrName(state);
  if (tagName === "") {
    return {
      TAG: "Error",
      _0: `I found a < but no tag name after it. Did you mean to write a tag like <say> or <remember>?`
    };
  }
  let e = parseAttributes(state);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let attrs = e._0;
  skipWhitespace(state);
  if (startsWith(state, "/>")) {
    advance(state, 2);
    return {
      TAG: "Ok",
      _0: [
        tagName,
        attrs,
        true
      ]
    };
  } else if (Primitive_object.equal(peek(state), ">")) {
    advance(state, 1);
    return {
      TAG: "Ok",
      _0: [
        tagName,
        attrs,
        false
      ]
    };
  } else {
    return {
      TAG: "Error",
      _0: `The <` + tagName + `> tag doesn't end properly. It should end with > or /> (for self-closing tags like <stop/>).`
    };
  }
}

function parseCloseTag(state) {
  if (!startsWith(state, "</")) {
    return {
      TAG: "Error",
      _0: `I expected a closing tag (like </say>) but didn't find one. Every opening tag needs a matching closing tag!`
    };
  }
  advance(state, 2);
  let tagName = parseAttrName(state);
  if (tagName === "") {
    return {
      TAG: "Error",
      _0: `I found </ but no tag name after it. Closing tags look like </say>.`
    };
  } else {
    skipWhitespace(state);
    if (Primitive_object.equal(peek(state), ">")) {
      advance(state, 1);
      return {
        TAG: "Ok",
        _0: tagName
      };
    } else {
      return {
        TAG: "Error",
        _0: `The closing tag </` + tagName + `> is missing its >. It should be </` + tagName + `>.`
      };
    }
  }
}

function parseNode(state) {
  skipWhitespaceAndComments(state);
  let e = parseOpenTag(state);
  if (e.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e._0
    };
  }
  let match = e._0;
  let attrs = match[1];
  let tagName = match[0];
  let nodeType = tagNameToNodeType(tagName);
  if (nodeType === undefined) {
    return {
      TAG: "Error",
      _0: `I don't know the tag <` + tagName + `>. ` + (`The tags I understand are: ` + "say, remember, ask, choose, when, otherwise, repeat, canvas, shape, add, subtract, stop" + `. `) + `Check your spelling!`
    };
  }
  if (match[2] || isSelfClosingTag(tagName)) {
    let attrDict = Object.entries(attrs).length > 0 ? attrs : undefined;
    return {
      TAG: "Ok",
      _0: {
        nodeType: nodeType,
        children: undefined,
        attributes: attrDict,
        content: undefined
      }
    };
  }
  if (isContainerTag(tagName)) {
    let e$1 = parseChildren(state, tagName);
    if (e$1.TAG !== "Ok") {
      return {
        TAG: "Error",
        _0: e$1._0
      };
    }
    let attrDict$1 = Object.entries(attrs).length > 0 ? attrs : undefined;
    return {
      TAG: "Ok",
      _0: {
        nodeType: nodeType,
        children: e$1._0,
        attributes: attrDict$1,
        content: undefined
      }
    };
  }
  let textContent = parseTextContent(state);
  skipWhitespaceAndComments(state);
  let e$2 = parseCloseTag(state);
  if (e$2.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: e$2._0
    };
  }
  let closeName = e$2._0;
  if (closeName.toLowerCase() !== tagName.toLowerCase()) {
    return {
      TAG: "Error",
      _0: `Oops! I found </` + closeName + `> but I was expecting </` + tagName + `>. Make sure every tag is closed with the right name!`
    };
  }
  let attrDict$2 = Object.entries(attrs).length > 0 ? attrs : undefined;
  let content = textContent === "" ? "" : textContent;
  return {
    TAG: "Ok",
    _0: {
      nodeType: nodeType,
      children: undefined,
      attributes: attrDict$2,
      content: content
    }
  };
}

function parseChildren(state, parentTagName) {
  let children = [];
  let error;
  let done = false;
  while (!done && error === undefined) {
    skipWhitespaceAndComments(state);
    if (isAtEnd(state)) {
      error = `I reached the end of the file but <` + parentTagName + `> was never closed! ` + (`Add </` + parentTagName + `> to close it.`);
    } else if (startsWith(state, "</")) {
      let e = parseCloseTag(state);
      if (e.TAG === "Ok") {
        let closeName = e._0;
        if (closeName.toLowerCase() !== parentTagName.toLowerCase()) {
          error = `I found </` + closeName + `> but I was expecting </` + parentTagName + `>. Tags need to be closed in order!`;
        } else {
          done = true;
        }
      } else {
        error = e._0;
      }
    } else if (startsWith(state, "<")) {
      let e$1 = parseNode(state);
      if (e$1.TAG === "Ok") {
        children = children.concat([e$1._0]);
      } else {
        error = e$1._0;
      }
    } else {
      let text = parseTextContent(state);
      if (text !== "") {
        error = `I found text "` + text + `" directly inside <` + parentTagName + `>, ` + (`but <` + parentTagName + `> should only contain other tags, not plain text.`);
      }
    }
  };
  let e$2 = error;
  if (e$2 !== undefined) {
    return {
      TAG: "Error",
      _0: e$2
    };
  } else {
    return {
      TAG: "Ok",
      _0: children
    };
  }
}

function parse(source) {
  let state = {
    source: source,
    pos: 0
  };
  let children = [];
  let error;
  while (!isAtEnd(state) && error === undefined) {
    skipWhitespaceAndComments(state);
    if (!isAtEnd(state)) {
      if (startsWith(state, "<")) {
        let e = parseNode(state);
        if (e.TAG === "Ok") {
          children = children.concat([e._0]);
        } else {
          error = e._0;
        }
      } else {
        let text = parseTextContent(state);
        if (text !== "") {
          error = `I found text "` + text + `" outside of any tag. ` + (`All text needs to be inside a tag like <say>` + text + `</say>.`);
        }
      }
    }
  };
  let e$1 = error;
  if (e$1 !== undefined) {
    return {
      TAG: "Error",
      _0: e$1
    };
  } else {
    return {
      TAG: "Ok",
      _0: {
        nodeType: "Program",
        children: children,
        attributes: undefined,
        content: undefined
      }
    };
  }
}

function parseExn(source) {
  let node = parse(source);
  if (node.TAG === "Ok") {
    return node._0;
  } else {
    return RescriptCore.panic(`Parse error: ` + node._0);
  }
}

function validate(source) {
  let msg = parse(source);
  if (msg.TAG === "Ok") {
    return "Ok";
  } else {
    return msg._0;
  }
}

export {
  makeState,
  isAtEnd,
  peek,
  advance,
  startsWith,
  skipWhitespace,
  skipComment,
  skipWhitespaceAndComments,
  tagNameToNodeType,
  isSelfClosingTag,
  isContainerTag,
  parseQuotedValue,
  parseAttrName,
  parseAttributes,
  parseTextContent,
  parseOpenTag,
  parseCloseTag,
  parseNode,
  parseChildren,
  parse,
  parseExn,
  validate,
}
/* No side effect */
